apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: mount-volume
          hostPath:
            path: /home/mount-point
        - name: server-key
          emptyDir: {}
      initContainers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: mount-volume
          mountPath: /home/mount-point
        - name: server-key
          mountPath: /home/server-key
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/sh"]
        args: 
        - "-c"
        - >
          cp /home/mount-point/generate-certs.sh /home/ &&
          chmod 0700 /home/generate-certs.sh &&
          /home/generate-certs.sh
      containers:
      - name: postgres
        securityContext:
          runAsUser: 999
        image: postgres
        volumeMounts:
          - name: mount-volume
            mountPath: /home/mount-point
          - name: server-key
            mountPath: /home/server-key
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: SSL_CA_FILE
          value: /home/server-key/minikube_postgres_root.crt
        - name: SSL_CERT_FILE
          value: /home/server-key/server.crt
        - name: SSL_KEY_FILE
          value: /home/server-key/server.key
        - name: PGSSLMODE
          value: verify-full
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-root-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-root-password
        args: 
        - "-c"
        - "ssl=on"
        - "-c"
        - "log_directory=/home/mount-point/logs/postgres"
        - "-c"
        - "ssl_ca_file=$(SSL_CA_FILE)"
        - "-c"
        - "ssl_cert_file=$(SSL_CERT_FILE)"
        - "-c"
        - "ssl_key_file=$(SSL_KEY_FILE)"
        - "-c"
        - "listen_addresses=*"
        - "-c"
        - "logging_collector=on"
        - "-c"
        - "log_destination=stderr"
        - "-c"
        - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
        - "-c"
        - "log_file_mode=0666"
        - "-c"
        - "log_min_messages=INFO"
        - "-c"
        - "log_error_verbosity=VERBOSE"
        
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
   - name: postgres
     port: 5432
     nodePort: 30432
  type: NodePort
  selector:
    app: postgres